apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vedantsharmascaler/app-of-apps-repo  # Replace with your actual GitHub account/repo URL
    path: .                                                  # Ensure this is the correct path to the directory with your apps
    targetRevision: main                                     # Replace "main" with the correct branch or tag instead of "HEAD"
    directory:
      recurse: true                                          # Recurse through the repository for subdirectories
  destination:
    server: https://kubernetes.default.svc                   # In-cluster Kubernetes API server
    namespace: argocd                                        # Ensure this is the intended target namespace for ArgoCD
  syncPolicy:
    automated:
      prune: true                                            # Remove resources no longer defined in the repository
      selfHeal: true                                         # Automatically sync if the state drifts

