apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vedantsharmascaler/argocd-example-apps  # Replace with your GitHub account if needed
    path: helm-guestbook                                  # Path within the repository
    targetRevision: master                                       # Replace "main" with the appropriate branch or tag
  destination:
    server: https://kubernetes.default.svc                     # In-cluster Kubernetes API server
    namespace: helm-guestbook                             # Target namespace
  syncPolicy:
    automated:
      prune: true                                              # Prune resources not in the source
      selfHeal: true                                           # Automatically fix drift
    syncOptions:
      - CreateNamespace=true                                   # Automatically create the namespace if it doesn't exist

